<a href="https://colab.research.google.com/github/lugiumarra/COGS108_Repo/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 

A= np.random.randint(10, size=(4,4))
B = np.random.randint(10, size=(4,4))

print("Matrix A is: \n", A)
print("Matrix B is: \n", B)

Matrix A is: 
 [[7 3 2 4]
 [3 1 4 1]
 [2 6 3 0]
 [0 6 1 4]]
Matrix B is: 
 [[9 8 8 2]
 [1 5 6 1]
 [5 9 3 0]
 [2 4 2 7]]


In [ ]:
A[0,:]

array([6, 2, 8, 1])

In [ ]:
A[1,:]

array([3, 7, 2, 7])

In [ ]:
A[:,0]

array([6, 3, 8, 4])

In [ ]:
A[:,3]

array([1, 7, 6, 6])

In [ ]:
A[1:,0]

array([3, 8, 4])

In [ ]:
A[:1,0]

array([6])

In [ ]:
A[2:,2]

array([8, 1])

In [ ]:
A[1:3,2]

array([2, 8])

In [ ]:
A[1:,1:]

array([[7, 2, 7],
       [2, 8, 6],
       [0, 1, 6]])

Explanation: This command is slicing the last 3 rows of A and the last three columns of A and returning the elements as an array. Since A is 4x4, the resulting array is 3x3 since row 0, and column 0 are sliced off of it. 

In [ ]:
A[:2,:3]

array([[6, 2, 8],
       [3, 7, 2]])

Explanation: This command is slicing the first two rows of A and the first three columns of A and returing these elements as an array. Since A is a 4x4 matirx, the resluting matix is 2x3 since the last 2 rows of A and the last column of A are not included in this slice. 

In [ ]:
np.dot(A[0,:],A[:,1])

42

Explanation: 

A[0,:] = [6,2,8,1]

A[:,1] = [2,7,2,0]

[6,2,8,1][2,7,2,0]$^T$ = <br>

6(2) + 2(7) + 8(2) + 1(0) = <br>
12 + 14 + 16 =
 **42**

In [ ]:
np.outer(A[0,:2],A[:2,1])

array([[12, 42],
       [ 4, 14]])

Explanation:

A[0,:2] = [6,2]

A[:2,1] = [2,7]

outer product $[6,2]^{T}$ [2,7] = 
 \begin{array}{cc}
6(2) & 6(7)\\
2(2) & 2(7)
\end{array} 

=\begin{array}{cc}
12 & 24\\
4 & 2
\end{array}


In [ ]:
A[:2,:2]@B[1:3,:]

array([[58, 10, 64,  2],
       [41, 17, 80,  7]])

Explanation: 

A[:2,:2] =  \begin{array}{cc}
6 & 2\\
3 & 7
\end{array}


B[1:3,:] =  \begin{array}{cccc}
9 & 1 & 8 & 0\\
2 & 2 & 8 & 1
\end{array}
<br><br>
A[:2,:2]@B[1:3,:] =  \begin{array}{cccc}
6(9) + 2(2)& 6(1) + 2(2) &6(8) + 2(8) & 6(0) + 2(1)\\
3(9) + 7(2)& 3(1) + 7(2)& 3(8) + 7(8)& 3(0) + 7(1)
\end{array}

= <br>
\begin{array}{cccc}
54 + 2 & 6 + 4& 48 + 16& 0 + 2\\
27 + 14 & 3 + 14& 24 + 56& 0 + 7
\end{array} 

=<br>
\begin{array}{cccc}
58& 10& 64&2\\
41 &17& 80& 7 
\end{array} 


What is wrong with the commands np.dot(A[:3,0],A[:,1]) and A[:2,:2]@B[:3,:]? <br>

>np.dot(A[:3,0],A[:,1]) cannot be computed becuase the first array has 3 rows while the second array has 4. Nothing could be multipled by the 4th element of the second array so the dot product cannot be computed.<br>

>A[:2,:2]@B[:3,:] cannot be computed because the first array has 2 rows and the second array has 4 columns and thus matrix multiplication is not possible. 

In [ ]:
def lowerfSub(A,b):
  n=len(A)
  x=np.zeros(n)
  A = np.array(A, float)

  for i in range(n):
    #x[i] = (b[i] - np.dot(A[i,:i], x[:i]))/A[i,i]
    x[i]=1/A[i,i]*(b[i]-np.dot(A[i,:i],x[:i]))
    #x[i] = (b[i] - np.sum(A[i,:i] * x[:i]))/A[i,i]
  print(np.allclose(A@x,b))
  return x

A=[[1,0,0,0],[2,3,0,0],[1,-1,9,0],[2,0,3,1]]
b=np.random.rand(4)

print(lowerfSub(A,b))
print(np.linalg.solve(A,b))
print(b)


True
[ 0.98011598 -0.34742938 -0.10717213 -0.78602388]
[ 0.98011598 -0.34742938 -0.10717213 -0.78602388]
[0.98011598 0.91794382 0.3629962  0.85269169]


In [ ]:
def innerGEWP(A):

    U = np.zeros((A.shape[0], A.shape[0]), dtype=np.double)
    L = np.eye(A.shape[0], dtype=np.double)
    
    for k in range(A.shape[0]):

        U[k, k:] = A[k, k:] - L[k,:k] @ U[:k,k:]
        L[(k+1):,k] = (A[(k+1):,k] - L[(k+1):,:] @ U[:,k]) / U[k, k]
      
    return L@U, L, U

def outerGEWP(A):
    B = np.copy(A)
    for k in range (len(A) - 1):
        B[k+1:, k] = B[k+1:, k]/B[k, k]
        B[k+1:, k+1:] -= np.outer(B[k+1:,k],B[k, k+1:])
    return B

def split(A):
  U=np.zeros((len(A),len(A)))
  L=np.eye(len(A))
  for i in range(len(A)):
    U[i,i:]=A[i,i:]
    L[i+1:,i]=A[i+1:,i]
  return L, U


A= np.random.rand(20,20)
B, L, U = innerGEWP(A)
#L, U = split(B)
X, Z = split(outerGEWP(A))




#Outer
print("outer:", np.allclose(X@Z, A)) 

#Inner
print("inner:", np.allclose(L@U,A))



outer: True
inner: True


In [ ]:
def gaussianELM(B):
  A=np.copy(B)
  n=len(A)
  for i in range(n-1):
    for j in range(i+1,n):
      A[j,i]=A[j,i]/A[i,i]
      for k in range(i+1,n):
        A[j,k]-= A[j,i]*A[i,k]
  return A

def LUfactorizeB(A):
    B = np.copy(A)
    for k in range (0, len(A) - 1):
        B[k+1:, k] = B[k+1:, k]/B[k, k]
        B[k+1:, k+1:] -= np.outer(B[k+1:,k],B[k, k+1:])
    return B

def outGE(A):
  #Get the number of rows
    U = A.copy()
    L = np.eye(A.shape[0], dtype=np.double)
    
    for i in range(A.shape[0]):
        L[i+1:, i] = U[i+1:, i] / U[i, i]
        U[i+1:] -=  (U[i+1:, i] / U[i, i])[:, np.newaxis] * U[i]
    return L@U, L, U

A= np.random.rand(20,20)
Y = LUfactorizeB(A)

In [ ]:
from time import process_time as pt
for i in range(10):
  A=np.random.rand(100,100)
  start=pt()
  gaussianELM(A)
  t=pt()-start
  start=pt()
  innerGEWP(A)
  print(t/(pt()-start))
  print("\n")

45.3497960203832


57.285987514568085


80.6244694944084


81.7425994289437


33.05887873540781


81.16384053047366


79.32312121658774


73.74286431694321


76.5399391623833


84.44612445558985




In [ ]:
from time import process_time as pt
for i in range(10):
  A=np.random.rand(100,100)
  start=pt()
  gaussianELM(A)
  t=pt()-start
  start=pt()
  outerGEWP(A)
  print(t/(pt()-start))
  print("\n")

81.83823451844607


51.723217428390704


96.04773475193093


53.73229439144173


56.70831377970642


53.828934294959446


43.39419010304672


46.78006803711537


100.86806832420525


50.444562197398035




In [ ]:
from time import process_time as pt
for i in range(10):
  A=np.random.rand(1000,1000)
  start=pt()
  outerGEWP(A)
  t=pt()-start
  start=pt()
  innerGEWP(A)
  print(t/(pt()-start))
  print("\n")

1.4663533128594852


1.7825096667820162


1.7769227071968596


1.8025554584313463


1.7379717660065424


1.7775603925333703


1.779489768432296


1.7730904113284678


1.6621007836078572


1.7670825428076486




In [ ]:
from time import process_time as pt

a = 0
for i in range(10):
  A=np.random.rand(100,100)
  start=pt()
  gaussianELM(A)
  t=pt()-start
  a = a + t
  print(t)

print("gauss average time:", a/(10))
print("\n")

a = 0
for i in range(10):
  A=np.random.rand(100,100)
  start=pt()
  innerGEWP(A)
  t=pt()-start
  a = a + t
  print(t)

print("inner average time:", a/(10))

0.22503510899991852
0.2198446900001727
0.21899088300006042
0.23496941200005494
0.23287685599984798
0.2313007089999246
0.2362354020001476
0.22694608400001925
0.21790807000002133
0.23342629600006148
gauss average time: 0.22775335110002287


0.02453802599984556
0.024221026999839523
0.024712544000067282
0.03627642900005412
0.023214714000005188
0.02421423600003436
0.024594863000174882
0.02126287000010052
0.024046442000098978
0.02637687899982666
inner average time: 0.025345803000004708


In [ ]:
a = 0
for i in range(10):
  A=np.random.rand(500,500)
  start=pt()
  outerGEWP(A)
  t=pt()-start
  a = a + t
  print(t)

print("outer average time:", a/(10))
print("\n")

a = 0
for i in range(10):
  A=np.random.rand(500,500)
  start=pt()
  innerGEWP(A)
  t=pt()-start
  a = a + t
  print(t)

print("inner average time:", a/(10))

8.704532501999893
8.638646610000023
8.73765424499993
8.621049990000074
8.711213154000006
8.666050308999957
8.628260749999981
8.635144234000109
8.700998095999921
8.56199582499994
outer average time: 8.660554571499983


8.212396923999904
8.159736287999976
8.355027352999969
8.274878557999955
8.313179751999996
8.267767465999896
8.404855729000019
8.281444775999944
8.35934148399997
8.197613818000036
inner average time: 8.282624214799966


In [ ]:
a = 0
for i in range(10):
  A=np.random.rand(100,100)
  start=pt()
  gaussianELM(A)
  t=pt()-start
  a = a + t
  print(t)

print("Guass average time:", a/(10))
print("\n")

a = 0
for i in range(10):
  A=np.random.rand(100,100)
  start=pt()
  outerGEWP(A)
  t=pt()-start
  a = a + t
  print(t)

print("outer average time:", a/(10))

0.2108089140001539
0.21626448699998946
0.23096761600004356
0.2207657690000815
0.21396327799993742
0.21518752299994048
0.2308055199998762
0.2225911499999711
0.21659571099985442
0.2304858680001871
Guass average time: 0.2208435836000035


0.02911973000004764
0.03713881500016214
0.02704172399990057
0.03445207100003245
0.024291895000033037
0.02678727800002889
0.027437917000042944
0.026654236000013043
0.028261929000109376
0.026992939000137994
outer average time: 0.02881785340005081
